### ISSUE TITLE
Provide submariner addon for OCM

### ISSUE THREAD

**Issue by SataQiu** [open-cluster-management-io/OCM#11]
Is anyone working on [submariner](https://submariner.io/) addon for OCM?

I'm interested in `submariner` right now, maybe I can help contribute.

**Comment by mikeshng** [comment]
Hi, there is a submariner addon available for ACM (a product that uses OCM as base). See: https://github.com/open-cluster-management/submariner-addon

They have not transition the repo to OCM upstream org yet. But maybe you can try using that addon and see if it works with OCM. Based on my quick look at the `go.mod`, I think it will most likely work.

FYI @nyechiel

**Comment by qiujian16** [comment]
maybe we should transition the repo to the upstream org, or at least provide a helm chart to deploy submariner addon
