### ISSUE TITLE
The similarities and differences between OCM and Rancher Fleet?

### ISSUE THREAD

**Issue by benson211** [open-cluster-management-io/ocm#116]
As shown in the title，what are the similarities and differences between OCM and Rancher Fleet? 
Is it a good choice to replace Rancher with OCM?

**Comment by mikeshng** [comment]
Hi, the main similarity is both architecture is based on pull model. The main differences is OCM is much more modular.
- OCM is focusing on developing and enhancing each individual API. You can see how much more powerful OCM APIs are compare to the Rancher fleet. For example, take a look at Placement and ManagedClusterSet in https://open-cluster-management.io/concepts/
- Other projects can pick and choose the OCM APIs they want to gain multicluster capability.
- Rancher seems to have tight coupling of GitOps. In OCM, we have many ways to provide optional GitOps support such as our native App addon and ArgoCD integration.

**Comment by benson211** [comment]
Thanks, is there any plan to provide the UI for multicluster management in this project?

**Comment by mikeshng** [comment]
There is a community project for VScode extension which provides some UI capabilities. See https://open-cluster-management.io/developer-guides/vscode-extension/ for more details.

As of now we have no other UI plans, we will have to rely on the community to provide some more UI contributions.
