### ISSUE TITLE
Document the limits on ManfiestWorks that can run in the hub cluster

### ISSUE THREAD

**Issue by anoop2811** [open-cluster-management-io/ocm#119]
As an operator, it would help us to size and determine the number of hubs that would be required to manage a fleet of hundreds of managed clusters where each of the managed clusters could be running thousands of workloads. 

It would help to know where the limitations are and what can be done on the observability front to be able to understand if limits are being reached in order to appropriately take action as needed

**Comment by qiujian16** [comment]
Update: @skeeey is starting tests on 50 clusters with different number of manifestworks.

**Comment by skeeey** [comment]
Current I used the https://github.com/open-cluster-management-io/multicluster-controlplane as the hub and tested the 50 clusters and  5000 manifestworks (`100 manifestworks/cluster`), the result can be found from
https://docs.google.com/spreadsheets/d/11GcIXAxPpQlu35VWnN5sVtqrtkM0EYm3rqj8sTz2Pvs/edit?usp=sharing


Next I will test
50 cluster + `200 manifestworks/cluster`
50 cluster + `500 manifestworks/cluster`
50 cluster + `1000 manifestworks/cluster`

And I will also run these when we use `clustermanager` as the hub scenario

**Comment by anoop2811** [comment]
I would be interested in knowing about the results of the 50 + > 1000 manifests/cluster

**Comment by skeeey** [comment]
@anoop2811 we have tested the above test cases, more details can be found from https://docs.google.com/spreadsheets/d/11GcIXAxPpQlu35VWnN5sVtqrtkM0EYm3rqj8sTz2Pvs/edit#gid=769720487

/cc @qiujian16

**Comment by anoop2811** [comment]
Thanks do you think increasing the clusters beyond 50 would still work with linear increase in cpu and memory?

**Comment by skeeey** [comment]
I think it should be
