### ISSUE TITLE
Clusteradm support install clustermanager and klusterlet by OLM.

### ISSUE THREAD

**Issue by xuezhaojun** [open-cluster-management-io/ocm#125]
From the feedback from the community, we found most of the users only use `clusteradm` to install. So it's better to add a subcommand in `clusteradm` to support OLM installation as a option.

**Comment by zhiweiyin318** [comment]
There are commands to install operators on the [artifacthub.io](https://artifacthub.io/) or [operatorhub.io ](https://operatorhub.io/)
https://operatorhub.io/operator/cluster-manager
https://operatorhub.io/operator/klusterlet
https://artifacthub.io/packages/olm/community-operators/cluster-manager
https://artifacthub.io/packages/olm/community-operators/klusterlet
clusteradm is always an easy way to install clustermanager and klusterlet, do not need to support OLM in clusteradm.
And I think the helm chart users are more than OLM, maybe we could consider to publish helm charts.
