### ISSUE TITLE
Test different *ks (e.g. eks, aks, gke) as the hub

### ISSUE THREAD

**Issue by skeeey** [open-cluster-management-io/ocm#126]
We need to test different *ks (e.g. eks, aks, gke) as the hub and doc the result

**Comment by ldpliu** [comment]
I test aks as hub cluster, and openshift cluster as spoke, it works fine.
Detail in : https://github.com/open-cluster-management-io/registration/issues/294

**Comment by skeeey** [comment]
for EKS , because of the https://github.com/aws/containers-roadmap/issues/1604, the EKS cannot sign a client cert for managed cluster, we may need to use clusteradmin to deploy a standalone controlplane as the hub to resolve this problem

**Comment by ohkinozomu** [comment]
Here is what I know about GKE:
- GKE Autopilot does not support CSRs and has the same problem as EKS. https://cloud.google.com/kubernetes-engine/docs/resources/autopilot-standard-feature-comparison#functional-comparison
- Since OCM uses webhook, the following firewall rules are required for private clusters. https://cloud.google.com/kubernetes-engine/docs/how-to/private-clusters#add_firewall_rules

**Comment by qiujian16** [comment]
@skeeey @ycyaoxdu I think we should provide an option for user to start a standalone controlplane with `clusteradm init`. It could be an experimental feature in clusteradm

**Comment by clyang82** [comment]
We may also support `clusteradm join --standalone` to use the standalone controlplane agent to register.

**Comment by mikeshng** [comment]
@reedjosh yes the issue is resolved by using the https://github.com/open-cluster-management-io/multicluster-controlplane project. 

CC the devs and knowledge experts: @qiujian16 @clyang82 @skeeey

**Comment by reedjosh** [comment]
Thank you for the update. I'll read more on the project as I can. It seems ATM the readme is mostly geared to devs of the project though?

No biggie, but if ya can could you give me a rundown on what that project is about?

**Comment by mikeshng** [comment]
> It seems ATM the readme is mostly geared to devs of the project though?

Yes, it's relatively new project. I will create a PR today to enhance the readme.

> No biggie, but if ya can could you give me a rundown on what that project is about?

Please see issue: https://github.com/open-cluster-management-io/ocm/issues/189
Few videos:
https://www.youtube.com/watch?v=S-EM2xC3-p0
https://www.youtube.com/watch?v=fTaU9dncgHY

> Seems it deploys a secondary K8s controlplane as the EKS one can't sign certs?

Yes, that's one of the use case.

@reedjosh

**Comment by reedjosh** [comment]
@skeeey @mikeshng I have added several issues on the mutlicluster-controlplane project.

Please review them when you have a chance. I'm a bit stuck atm.

https://github.com/open-cluster-management-io/multicluster-controlplane/issues/100
https://github.com/open-cluster-management-io/multicluster-controlplane/issues/99
https://github.com/open-cluster-management-io/multicluster-controlplane/issues/98

Thank you!

**Comment by clyang82** [comment]
Thanks @reedjosh for your feedback. I will look at today.

**Comment by mikeshng** [comment]
@reedjosh I know you are not a fan of the clusteradm tool but we have a PR coming soon that will help init the `mulistercluster-controlplane`. See https://github.com/open-cluster-management-io/clusteradm/pull/336

**Comment by ohkinozomu** [comment]
GKE Autopilot now support CSR under restrictions.
https://cloud.google.com/release-notes#e89599ea

I have not yet confirmed that OCM works.

**Comment by aii-nozomu-oki** [comment]
Unfortunately, due to GKE Autopilot's limitations, OCM still doesn't work.
We need to continue using GKE Standard.

version: 1.27.3-gke.100

```
I1113 02:58:40.268803       1 event.go:298] Event(v1.ObjectReference{Kind:"Namespace", Namespace:"open-cluster-management-agent", Name:"open-cluster-management-agent", UID:"", APIVersion:"v1", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'NoValidCertificateFound' No valid client certificate for BootstrapClientCertController@cluster:k3s01 is found. Bootstrap is required
E1113 02:58:40.602894       1 base_controller.go:272] BootstrapClientCertController@cluster:k3s01 reconciliation failed: admission webhook "warden-validating.common-webhooks.networking.gke.io" denied the request: GKE Warden rejected the request because it violates one or more constraints.
Violations details: {"[denied by autogke-csr-limitation]":["Creating CSRs which use a username with 'system:' prefix for the common name are not allowed. CN: 'system:open-cluster-management:k3s01:58m6f'.","Creating CSRs which use a 'system:' prefix for the Organization are not allowed. O: 'system:open-cluster-management:k3s01'.","Creating CSRs which use a 'system:' prefix for the Organization are not allowed. O: 'system:open-cluster-management:managed-clusters'."]}
Requested by user: 'system:serviceaccount:open-cluster-management:cluster-bootstrap', groups: 'system:serviceaccounts,system:serviceaccounts:open-cluster-management,system:authenticated'.
```
