### ISSUE TITLE
Request for new Release cut for the Add-ons Cluster-proxy, Managed-ServiceAccount and Cluster-Gateway

### ISSUE THREAD

**Issue by suresh-j2** [open-cluster-management-io/ocm#138]
**Describe the bug**
I would like to request a new release cut for the add-ons. cluster-proxy, managed-serviceaccount and cluster-gateway

**To Reproduce**

**Expected behavior**

**Environment ie: OCM version, Kubernetes version and provider:**

**Additional context**
Currently the Add-on helm charts are not updated for few months and hence its not working as per the document.

**Comment by xuezhaojun** [comment]
@suresh-j2  Hello, "its not working as per the document", do you mean this one: https://open-cluster-management.io/scenarios/pushing-kube-api-requests/ ?

**Comment by suresh-j2** [comment]
@xuezhaojun yes thats right. Also, was facing issue initially doc as well. https://open-cluster-management.io/developer-guides/addon/.  The release version is not having certain packages used in the code example.

**Comment by xuezhaojun** [comment]
Hi, @suresh-j2, we're going to release 0.3.0 for cluster-proxy and managed-serviceaccount:
* https://github.com/open-cluster-management-io/cluster-proxy/pull/161
* https://github.com/open-cluster-management-io/managed-serviceaccount/pull/64

After the Pull Request is merged, we are going to update the document as well.

I notice you said you're facing problems in https://open-cluster-management.io/developer-guides/addon/, do you mind sharing what specific issue you're facing?

**Comment by suresh-j2** [comment]
Thanks @xuezhaojun .  Sorry the link was wrong. I guess, i was facing issue while trying out this examples. https://github.com/open-cluster-management-io/cluster-proxy/blob/main/examples/access-exported-services/main.go. These code refers to some of the methods which is not released. For ex, GetProxyHost. I believe with the new release this should also be fixed.

**Comment by xuezhaojun** [comment]
Got it, I will notify in this thread once new release is done.
