### ISSUE TITLE
Enhance the managedCluster deletion process 

### ISSUE THREAD

**Issue by zhiweiyin318** [open-cluster-management-io/ocm#140]
**Describe the enhancement**
currently we need to clean up the addons and manifestworks before delete managedCluster manually, so we need to refactor the deletion process of the managedCluster to make it easy to clean up the related resources.

**Comment by qiujian16** [comment]
I think we need to consider several different use cases:
1. after creation of manifestwork/addons, user deletes the managed cluster on the hub.
2. after creation of manifestwork/addons, user deletes klusterlet on the spoke without any intervention on the hub
3. after import some clusters and creation of manifestwork/addons, user delete clustermanager on the hub

**Comment by qiujian16** [comment]
@zhiweiyin318 I think this is completed.

**Comment by zhiweiyin318** [comment]
added a featureGate `ResourceCleanup` for the registration on Hub to enable the addon and mainifestworks cleanup after cluster is deleted. default is to disable the featureGate. 
the deletion order like this: delete addon firstly, and then delete manifestworks after there is no addons.
