### ISSUE TITLE
Document the hosted klusterlet setup

### ISSUE THREAD

**Issue by rolandkool** [open-cluster-management-io/ocm#194]
**Describe the enhancement**

Running Klusterlet in hosted mode is not very well documented. There are some hints to be found here:
https://github.com/open-cluster-management-io/registration-operator#deploy-spokeklusterlet-with-hosted-mode
https://github.com/open-cluster-management-io/clusteradm/pull/289

This feature deserves a proper mention in the official [installation documentation](https://open-cluster-management.io/getting-started/installation/)

**Comment by zhujian7** [comment]
@rolandkool I added some doc for running Klusterlet in hosted mode, https://open-cluster-management.io/getting-started/installation/register-a-cluster/#bootstrap-a-klusterlet-in-hosted-modeoptional

will close this issue first, feel free to reopen it if something is unclear.
/close
