### ISSUE TITLE
Document how to make a cluster a spoke of multiple hubs

### ISSUE THREAD

**Issue by rolandkool** [open-cluster-management-io/ocm#195]
**Describe the enhancement**

OCM is quite flexible. It is possible for a cluster to be both a Hub and a Spoke at the same time. It is also possible for a cluster to be a Spoke of multiple Hubs. However, how to set this up is not documented. It would be helpful to do so. 

Some steps I had to take to make it work are:
* create a unique new namespace for second hub called `open-cluster-management-agent-<newcluster>`
* manually create the `bootstrap-hub-config` secret. I used another one as basis and made the necessary adjustments like updating the token. This step in particular requires some explanation.
* create a `klusterlet` resource with the name of <newcluster> and pointed it to the new namespace

**Comment by elgnay** [comment]
https://github.com/open-cluster-management-io/ocm/pull/304
https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/pull/392

**Comment by elgnay** [comment]
Closing the issue for the proposed doc has been merged.
