### ISSUE TITLE
adding a time to live (TTL) option for managed-serviceaccount

### ISSUE THREAD

**Issue by TheRealHaoLiu** [open-cluster-management-io/OCM#22]
I been experimenting with the [managed-serviceaccount ](https://github.com/open-cluster-management-io/managed-serviceaccount) project from OCM and found it to be incredibly useful

for my usecase I leverage the managed-serviceaccount controller to create on-demand serviceaccount than use ManifestWork to create role/rolebinding on managedcluster to grant my serviceaccount RBAC permission.

the managed-serviceaccount and the manifestwork is short lived and is deleted when my workflow is done, but sometime i found that my workflow exit prematurely and the cleanup is not explicitly performed by my workflow (i know its my own problem but...)

it would be nice if the managed-serviceaccount resource can have a expiration time so that after expiration the managed-serviceaccount is deleted automatically

**Comment by TheRealHaoLiu** [comment]
@qiujian16 @yue9944882 any thoughts about adding this?

**Comment by qiujian16** [comment]
I think it make sense the token in managed-sa to expire (to not rotate any more). I am less sure about auto-deleting the resource. Maybe you could have an ownerref from manifestwork to managed-sa or vice versa since it seems the lifecycle of the two resource in this case are the same.

**Comment by TheRealHaoLiu** [comment]
can u elaborate your concern about having the managed-sa being auto-deleted?

**Comment by yue9944882** [comment]
@TheRealHaoLiu are you worrying about the potential leakage of the projected service-account tokens from those unfinished jobs? how about we set a more reasonable validity for the projected token and explicitly disable the rotation:

https://github.com/open-cluster-management-io/managed-serviceaccount/blob/a5e95f8951063bb9b045519555aca22d82ce7bdb/api/v1alpha1/managedserviceaccount_types.go#L76-L80

so even though the projected token (along w/ its managed sa object) will not be auto-deleted from hub cluster, the token will be expired after the validity period. i suppose "leaving an expired managed sa token" is almost equal to "auto-deleting the managed sa after ttl", wdyt?

**Comment by qiujian16** [comment]
i think it is done already, can we close this @TheRealHaoLiu ?
