### ISSUE TITLE
Event based manifestwork

### ISSUE THREAD

**Issue by skeeey** [open-cluster-management-io/ocm#224]
**Describe the enhancement**

In this enhancement,  we will investigate the possibility to treat ManifestWork as an eventing based mechanism rather than a Kubernetes style API. 

Tasks

- [ ] Investigate how to support to deliver the manifests between hub and spoke based on event
- [ ] Investigate how to do authentication and authorize for hub and spoke on the event broker

**Comment by morvencao** [comment]
drafted a KEP for this: https://github.com/open-cluster-management-io/enhancements/pull/97
PTAL

**Comment by skeeey** [comment]
The KEP has been merged
The lib has implemented https://github.com/open-cluster-management-io/api/tree/main/cloudevents
