### ISSUE TITLE
Hub cluster HA solution proposal

### ISSUE THREAD

**Issue by ArenaSu** [open-cluster-management-io/ocm#26]
The scenario encountered in production environment is that:

1. Hub cluster hc1 managed some managed clusters and many manifest works also many addons are deployed.
2. Hub cluster hc2 was installed as a backup.
2. Hub cluster encountered a critical error that could not recover for a short time.
3. We must join the managed clusters to Hub cluster hc2 and recovered OCM resources in Hub cluster hc2

Hub cluster HA solution proposal architecture is shown below:
![image](https://user-images.githubusercontent.com/21214629/150552859-ce188b97-9425-4df2-ab56-ff611c1939ab.png)

Of course, OCM resources such as manifest works deployed in managed clusters  should save meta data in annotaions or somewhere else.

Whether this solution is feasible ?

**Comment by qiujian16** [comment]
In this case we do not need to unjoin and join again. If we change the bootstrapKubconfig secret, then klusterlet will connect to the second hub. However, we do not have a clustercmd command to do that yet. Maybe something like

```
clusteradm rejoin --hub-apiserver second-hub --token xxx
```

And it just update the bootstrap kubeconfig secret.

/kind feature

**Comment by ArenaSu** [comment]
> In this case we do not need to unjoin and join again. If we change the bootstrapKubconfig secret, then klusterlet will connect to the second hub. However, we do not have a clustercmd command to do that yet. Maybe something like
> 
> ```
> clusteradm rejoin --hub-apiserver second-hub --token xxx
> ```
> 
> And it just update the bootstrap kubeconfig secret.
> 
> /kind feature

Ok, it can achieve the same goal. And what i am concerned about is recovery of resources such as manifest work.

**Comment by qiujian16** [comment]
Right, I think we could create a solution scenario in this repo by using Velero as an example. WDYT?
