### ISSUE TITLE
Proxy read/write to multiple clusters based on placement with cluster-proxy addon

### ISSUE THREAD

**Issue by qiujian16** [open-cluster-management-io/ocm#268]
**Describe the enhancement**

With the discussion here https://kubernetes.slack.com/team/U0LE4HDDH, it is an interesting idea to allow cluster-proxy to proxy certain request to multiple clusters based on placement. e.g.
- list resources from multiple clusters based on the placement.

It will not make sense for request like get logs/exec/update/patch to across multiple clusters.

There is some potential problem we need to consider:
1. request failure handling
2. different version of the clusters

**Comment by qiujian16** [comment]
cc @xuezhaojun

**Comment by xuezhaojun** [comment]
@qiujian16 The discussion link doesn't lead to a right place, would you like to update it?
