### ISSUE TITLE
Support ClusterLabels

### ISSUE THREAD

**Issue by aii-nozomu-oki** [open-cluster-management-io/ocm#269]
**Describe the enhancement**
I would like to manage ManagedCluster using labels.
Currently, this is possible through, for example, kubectl label, but it would be useful to accomplish this through an OCM ecosystem such as clusteradm.

Related issues/pull requests:
https://github.com/open-cluster-management-io/registration/issues/225
https://github.com/open-cluster-management-io/api/pull/252
https://github.com/open-cluster-management-io/ocm/pull/234

**Comment by qiujian16** [comment]
Do you intend to allow setting the label of the cluster when the first bootstrap?

**Comment by aii-nozomu-oki** [comment]
Yes, what I finally want is `clusteradm join --cluster-labels=[key=value]`.
To accomplish just that, maybe support at the API level is not needed.

**Comment by qiujian16** [comment]
cc @xuezhaojun
