### ISSUE TITLE
Klog flags disppeared because of component-base updates.

### ISSUE THREAD

**Issue by xuezhaojun** [open-cluster-management-io/OCM#31]
## Issue:
We are using the following pattern to setup logs in many repo currently:

```go
        pflag.CommandLine.SetNormalizeFunc(utilflag.WordSepNormalizeFunc)
	pflag.CommandLine.AddGoFlagSet(goflag.CommandLine)

	logs.InitLogs()
	defer logs.FlushLogs()
```

But it seems `klog` part has been missed in the latest version:
```
➜  helloworld git:(f3917ca) ✗ ./helloworld controller --help
Start the addon controller

Usage:
  addon controller [flags]

Flags:
      --config string                    Location of the master configuration file to run from.
      -h, --help                             help for controller
      --kubeconfig string                Location of the master configuration file to run from.
      --listen string                    The ip:port to serve on.
      --namespace string                 Namespace where the controller is running. Auto-detected if run in cluster.
      --terminate-on-files stringArray   A list of files. If one of them changes, the process will terminate.
```

The above process, it should have some `klog` flag such as `--v`.

## Reason

The reason for this issue may be in the latest version `component-base`, it using a customized FlagsSet:

https://github.com/kubernetes/component-base/blob/30d23418100a70c7ea34979e1fe87da620b84025/logs/logs.go#L53

## Solution

A way to solve this issue could be:
```go
        pflag.CommandLine.SetNormalizeFunc(utilflag.WordSepNormalizeFunc)
	pflag.CommandLine.AddGoFlagSet(goflag.CommandLine)

	logs.AddFlags(pflag.CommandLine) // Use this line to add default FlagSet into component-base.

	logs.InitLogs()
	defer logs.FlushLogs()
```

**Comment by xuezhaojun** [comment]
Update another solution:

```
command := NewLoggerCommand()
code := cli.Run(command)
```

**Comment by xuezhaojun** [comment]
Another PR related to this issue：https://github.com/open-cluster-management-io/cluster-proxy/pull/73

**Comment by xuezhaojun** [comment]
The code also works and with less klog flags:
```go
logs.NewOptions().AddFlags(pflag.CommandLine)
```

**Comment by zhiweiyin318** [comment]
this related changes in k8s.io/component-base/logs 
https://github.com/kubernetes/kubernetes/pull/105076
https://github.com/kubernetes/kubernetes/commit/21d1bcd6b8498370832fa76f680d3de56837bc83
the suggested example:
https://github.com/kubernetes/kubernetes/blob/428ec843a5f689f9e30d22968ee1eb6d106f6ffb/staging/src/k8s.io/component-base/logs/example/cmd/logger.go#L39
`logs.NewOptions().AddFlags(pflag.CommandLine)` will only registry --v and --vmodule of vlogs.

**Comment by zhiweiyin318** [comment]
@qiujian16  I think registration-operator/ registration/work/placement repo need to fix this issue too
