### ISSUE TITLE
add more e2e and integration test for manifestworkreplicaset rollout

### ISSUE THREAD

**Issue by haoqing0110** [open-cluster-management-io/ocm#327]
**Describe the enhancement**
A clear and concise description of what the enhancement request is.

When trying the [RolloutConfig](https://github.com/open-cluster-management-io/api/blob/main/cluster/v1alpha1/types_rolloutstrategy.go#L54) of manifestworkreplicaset, meet below issues
- when the type is `ProgressivePerGroup` and the `MinSuccessTime` meets, the rollout doesn't continue to the next group
- when the failure exceeds `MaxFailures` the rollout doesn't stop.
 
need more  e2e and integration tests for manifestworkreplicaset rollout, to verify if the above feature works and this could also be an example for the usage.

**Comment by haoqing0110** [comment]
cc @haowells

**Comment by haowells** [comment]
both work-controller on hub and spoke cluster have this error messages
`E1211 12:54:27.375595       1 base_controller.go:266] "ManifestWorkReplicaSetController" controller failed to sync "default/guestbook-progressive-failure-pause", err: Operation cannot be fulfilled on manifestworkreplicasets.work.open-cluster-management.io "guestbook-progressive-failure-pause": the object has been modified; please apply your changes to the latest version and try again`
the workaround to let rollout continue is keep annotating MWRS object..

**Comment by haoqing0110** [comment]
The mentioned issues are fixed and more testing cases are added by PR https://github.com/open-cluster-management-io/ocm/pull/337, feel free to have a try. @haowells

**Comment by haowells** [comment]
@haoqing0110  thanks your effort !
