### ISSUE TITLE
Create a solution scenario on how is the placement used in OCM

### ISSUE THREAD

**Issue by qiujian16** [open-cluster-management-io/ocm#33]
We should have solution scenarios to describe:
- How user can extend placement scheduling.
- How user can use placement to schedule their workload.
- How to use placement and other opensource tools to do workload or storage disaster recovery.
- How to do cluster maintainence and its implication on placement

**Comment by haoqing0110** [comment]
How user can use placement to schedule their workload.
https://github.com/open-cluster-management-io/clusteradm/pull/247
https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/pull/273

**Comment by berenss** [comment]
does the word `schedule` mean that I can use **date**/**time** as part of placement?

**Comment by haoqing0110** [comment]
@berenss placement does not support "date/time" so far. Any use case for this feature?

**Comment by berenss** [comment]
Some examples could be:
 * create cluster.. scheduled during off-peak load times
 * hibernate clusters.. every evening 
 * upgrade clusters.. when stable channel has a release and label `prod` on Saturdays
 * unused cluster claims should expire automatically at the end of week
 * app deploys.. only deploy to `prod` on weekend
 * policy inform all the time, policy enforce only during evening and weekend

**Comment by qiujian16** [comment]
this may not be in the scope of the placement API, but a another API object that manipulate placement or cluster (taints) based on time schedule.

**Comment by haoqing0110** [comment]
Task progress:

- [x] How user can extend placement scheduling. https://open-cluster-management.io/scenarios/extend-multicluster-scheduling-capabilities/
- [x] How user can use placement to schedule their workload. https://open-cluster-management.io/scenarios/distribute-workload-with-placement/
- [ ] How to use placement and other opensource tools to do workload or storage disaster recovery.
- [ ] How to do cluster maintainence and its implication on placement

**Comment by haoqing0110** [comment]
Task progress:

- [x] How user can extend placement scheduling. https://open-cluster-management.io/scenarios/extend-multicluster-scheduling-capabilities/
- [x] How user can use placement to schedule their workload. https://open-cluster-management.io/scenarios/distribute-workload-with-placement/
- [x] How to use placement and other opensource tools to do workload or storage disaster recovery. https://open-cluster-management.io/scenarios/migrate-workload-with-placement/
- [x] How to do cluster maintainence and its implication on placement https://open-cluster-management.io/scenarios/migrate-workload-with-placement/

**Comment by haoqing0110** [comment]
Close as all the sub-tasks are done.
