### ISSUE TITLE
What's the relationship between Placement and ManifestWork

### ISSUE THREAD

**Issue by chenchun** [open-cluster-management-io/ocm#335]
Walking through all the documents, I can't tell there is a specific explain about the connections of Placement and ManifestWork. Is a Placement applies to all ManifestWorks in its `cluster` namespace? If it does, what is gonna happen there are multiple conflict `Placement`?

**Comment by qiujian16** [comment]
there is no connection between ManifestWork and Placement. They are independent primitives. ManifestWork is to describe "I want to apply some resource on a single cluster" where a cluster is represented by a cluster namespace. Placement is to describe "I want to select some cluster". 

The namespace of placement is irrelevant to the namespace of ManifestWork. Namespace of the Manifestwork in OCM context is called "cluster namespace" which can be regarded as certain namespace for a cluster. The namespace of the placement can be any namespace for user to define their workload. 

To connect with ManifestWork/Placement, you would want to use `ManifestWorkReplicaSet`/`Placement` together which should be in the same namespace,
