### ISSUE TITLE
Why submit ManifestWork instead of native Workload

### ISSUE THREAD

**Issue by chenchun** [open-cluster-management-io/ocm#336]
Consider all the cons such as users have to learn a new API ManifestWork/ManifestWorkReplicaSet and resource race, defaulting/immutable fields, i.e. that are documented in https://open-cluster-management.io/concepts/manifestwork... what are the main pros that makes OCM decide to summit ManifestWork instead of unwrapped native workload such as Deployment, StatefulSet...?

**Comment by qiujian16** [comment]
you actually can use `clusterctl create work xx -f xxx.yaml` to submit native resource. OCM is running on an existing k8s cluster as the hub cluster, so submit native resource to the hub cluster only means create the exact workload on the hub cluster.
