### ISSUE TITLE
How do I run argoCD with OCM

### ISSUE THREAD

**Issue by qiujian16** [open-cluster-management-io/OCM#35]
we should have a solution scenario to describe how user can run argocd on OCM and to multiple cluster gitops.

/assign @elgnay

**Comment by nasirudheen** [comment]
Hi !
Any update on this ? searching for help on this returns many blogs and docs but unfortunately all of those are openshif/ACM specific.
Any pointers ?
Thanks,
Nasir

**Comment by elgnay** [comment]
Hi @nasirudheen, we're still working on it. Just like ACM does, OCM can integrate with ArgoCD by leveraging ArgoCD ApplicationSet with [Cluster Decision Resource Generator](https://argocd-applicationset.readthedocs.io/en/stable/Generators-Cluster-Decision-Resource/). The basic ideal is 
- User imports clusters into OCM hub as managedclusters;
- User registers those clusters to ArgoCD (ACM can do it automatically);
- User organizes managedclusters with managedclustersets;
- User binds some managedclustersets to a workload namespace by creating managedclustersetbindings;
- User creates a Placement in the workload namespace to select some managedclustersets;
- User creates an ApplicationSet in the workload namespace with reference to the cluster decisions of the Placement by using Cluster Decision Resource Generator;
- The app will be deployed to the selected managedclusters;
- Once the cluster decisions of the Placement change for some reason, like cluster offline, ArgoCD will deploy the application to the new selected clusters;

**Comment by elgnay** [comment]
Done. Added the following two doc:
- A scenario: https://open-cluster-management.io/scenarios/integration-with-argocd/
- A solution: https://github.com/open-cluster-management-io/OCM/tree/main/solutions/deploy-argocd-apps
