### ISSUE TITLE
Migrate add-ons to be managed by addon-manager

### ISSUE THREAD

**Issue by haoqing0110** [open-cluster-management-io/ocm#355]
**Describe the enhancement**

**In OCM v0.11.0,** we introduced a new component called `addon-manager` to manage the add-on agent lifecycle. With this introduced, the addon agent has 2 ways to maintain the lifecycle:
- Let the addon controller itself manage by using framework code (the existing way).
- Let the `addon-manager` manage by defining `spec.installStrategy` in  `ClusterManagementAddOn`.

To avoid conflict, we also introduced annotation `addon.open-cluster-management.io/lifecycle` in `ClusterManagementAddOn` to control whether the addon lifecycle is managed by self (framework) or `addon-manager`. 

The `addon-manager` is disabled by default in OCM v0.11.0 and add-on is by default managed by self.  

**In OCM v0.12.0,** the `addon-manager` is enabled by default and the addon is still default managed by self.

In the future, we plan to make the addons by default [managed by `addon-manager`](https://open-cluster-management.io/developer-guides/addon/#managing-the-add-on-agent-lifecycle-by-addon-manager), so here is the addon-framework and addon-manager roadmap and migration plan.

------

**OCM v0.12.0** (released)
- The `addon-manager` supports the latest addon API.
- The `addon-manager` is default enabled.
- The addon is default managed by self (`addon-framework`).

**addon-framework 0.8.0** (released)
- Supports the latest addon API.

---

**OCM v0.13.0** (released)
- The addon is default managed by self (`addon-framework`).
- The minimal supported addon-framework version is v0.8.0.

**Addon-framework 0.9.0** (released)
- Mark [WithInstallStrategy()](https://github.com/open-cluster-management-io/addon-framework/blob/release-0.9/pkg/addonfactory/addonfactory.go#L85) as deprecated.
- The framework will force add annotation `addon.open-cluster-management.io/lifecycle: self` if the addon calls `WithInstallStrategy()`. 
- The framework requires `patch` permission on `ClusterManagementAddon`.

**Addon-framework 0.8.1** (released)
- The framework will force add annotation `addon.open-cluster-management.io/lifecycle: self` if the addon calls `WithInstallStragegy()`. 
- The framework requires `patch` permission on `ClusterManagementAddon`.

---

**OCM v0.14.0**
- The addon is default managed by self (`addon-framework`).
- The minimal request addon-framework version is v0.8.1.
- `Addon-manager` will add annotation `addon.open-cluster-management.io/lifecycle: addon-manager` if `self` is not set.

**Addon-framework 0.10.0**
- Remove duplicate config controller code in framework. 
- Remove [WithInstallStrategy()](https://github.com/open-cluster-management-io/addon-framework/blob/main/pkg/addonfactory/addonfactory.go#L84) func in framework. 
- If use addon-framework, remove annotation `addon.open-cluster-management.io/lifecycle: self`.  

---

**OCM future** https://github.com/open-cluster-management-io/ocm/issues/510 
- The addon is default managed by `addon-manager`.
- The minimal supported addon-framework version is v0.8.1.

**Comment by haoqing0110** [comment]
cc @qiujian16 @zhiweiyin318 @zhujian7

**Comment by zhujian7** [comment]
@haoqing0110 Can you add a link to the code for `WithInstallStrategy()` in the description above? So the user can know which specific function was called that will be impacted?

**Comment by qiujian16** [comment]
@haoqing0110 i think it is done, right?

**Comment by haoqing0110** [comment]
@qiujian16 we have finished the target in Addon-framework 0.10.0, I think the final goal is to make "the addon is default managed by addon-manager". Need another release to remove the code to force add the annotation `addon.open-cluster-management.io/lifecycle: addon-manager` and addon is default managed by addon-manager.

**Comment by qiujian16** [comment]
maybe create another issue to track this.

**Comment by haoqing0110** [comment]
https://github.com/open-cluster-management-io/ocm/issues/510 will trace the follow-up task.
