### ISSUE TITLE
现在有没有企业已经在使用OCM，有生产环境的实践吗？

### ISSUE THREAD

**Issue by mrningyang** [open-cluster-management-io/ocm#36]
现在有没有企业已经在使用OCM，有生产环境的实践吗？谢谢

**Comment by mikeshng** [comment]
@qiujian16 @yue9944882 I think he is asking about production usage of OCM. My Chinese is not that good. Could you please answer him? Thanks.

**Comment by qiujian16** [comment]
@mrningyang  有一些企业在使用OCM哈 红帽主要是基于OCM构建了一个多集群管理的工具，在许多企业（主要是通讯，金融）生产环境都有部署。主要的场景是通过OCM管理多个openshift集群，进行集群的升级，扩缩容等。通过OCM部署工作负载和环境配置等。

@yue9944882 应该有一些其他方面的信息^^

**Comment by yue9944882** [comment]
@mrningyang OCM是阿里云公有云专有云产品都采用且提供商品服务的多集群管理引擎，同时在输出给一些SaaS公司使用。

另外麻烦尽可能在社区中使用英语，这样其他社区的用户可以通过信息检索参考到这里的信息，多谢贡献。

> Appreciated if you can translate the content into English so that future visitors can refer to the content in this thread, machine-translation is also acceptable. Thanks for the contribution.

**Comment by mrningyang** [comment]
> @mrningyang OCM是阿里云公有云专有云产品都采用且提供商品服务的多集群管理引擎，同时在输出给一些SaaS公司使用。
> 
> 另外麻烦尽可能在社区中使用英语，这样其他社区的用户可以通过信息检索参考到这里的信息，多谢贡献。
> 
> > Appreciated if you can translate the content into English so that future visitors can refer to the content in this thread, machine-translation is also acceptable. Thanks for the contribution.

我想问下，因为OCM只是提供了一些核心的组件，但是并没有提供更高层次的方案和架构，比如如何将k8s 资源利用placement和manifestwork来进行动态多集群编排，阿里云使用的是kubeVela吗，看起来要将OCM投入到生成环境还需要很多工作要做。
