### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by tamalsaha** [open-cluster-management-io/ocm#362]
**Describe the enhancement**
Many of the addons don't provide arm64 images. Please consider providing arm64 images.

**Comment by qiujian16** [comment]
cc @zhujian7 @xuezhaojun

**Comment by qiujian16** [comment]
/assign @zhujian7 for managed-serviceaccount

will create another one for cluster-proxy @xuezhaojun

**Comment by xuezhaojun** [comment]
Hi, @tamalsaha I checked the repos of cluster-proxy and MSA and saw there are already arm64 images exist, is there any extra support you need in this case?

https://quay.io/repository/open-cluster-management/cluster-proxy?tab=tags
https://quay.io/repository/open-cluster-management/managed-serviceaccount?tab=tags&tag=latest

**Comment by qiujian16** [comment]
/close

seems this has been done.
