### ISSUE TITLE
Optimize image size

### ISSUE THREAD

**Issue by tamalsaha** [open-cluster-management-io/ocm#363]
**Describe the enhancement**
Various sub projects (eg: managed-serviceaccount) build separate binary for agent and manager instead of one binary with sub commands. This results in docker image having 2x the size than it should be.

Please consider producing one binary from a repo to reduce image size. This will speed up the release process. This will also simplify supporting [arm64 arch](https://github.com/open-cluster-management-io/ocm/issues/362).

**Comment by zhujian7** [comment]
Fix PR for the managed service account: https://github.com/open-cluster-management-io/managed-serviceaccount/pull/121

**Comment by qiujian16** [comment]
this PR is merged. Close this one. We can create a separated issue for another sub project 

/close
