### ISSUE TITLE
Supporting DaemonSet with AddOnTemplate

### ISSUE THREAD

**Issue by skeeey** [open-cluster-management-io/ocm#368]
Supporting DaemonSet with AddOnTemplate

e.g. I want to use `AddOnTemplate` to deploy Kepler, but Kepler is based on deamonset, so I have to use the manifestworkreplicaset as a workaround

https://github.com/stolostron/edge-innovation/blob/main/kepler-acm/kepler/manifestworkreplicaset.yaml

**Comment by zhujian7** [comment]
@skeeey I think this is finished, you can have a try with the latest ocm.
