### ISSUE TITLE
[GSoC 2024] Scheduling AI workload among multiple clusters

### ISSUE THREAD

**Issue by haoqing0110** [open-cluster-management-io/ocm#369]
This is one of [GSoC 2024](https://github.com/cncf/mentoring/blob/main/programs/summerofcode/2024.md#open-cluster-management) projects. 

**Announcement**
https://github.com/cncf/mentoring/discussions/1221 

**Google Summer of Code 2024 Timeline**
https://developers.google.com/open-source/gsoc/timeline

**Description** 

Open Cluster Management (OCM) focuses on multicluster and multicloud management scenarios for Kubernetes applications. Open APIs are evolving within this project for cluster registration, workload distribution, dynamic placement of policies and workloads, and much more. The placement concept is used to dynamically select a set of clusters so that higher level users can either replicate Kubernetes resources to the member clusters or run their advanced workload. For example: as an application developer, I can deploy my workload to clusters with the most allocatable memory and CPU.

Now, with the rise of AI technology, there’s a growing need to schedule AI workload based on GPU/TPU resources. In this project we want you to use the placement [extensible scheduling mechanism](https://open-cluster-management.io/scenarios/extend-multicluster-scheduling-capabilities/) to implement a GPU/TPU resource collector addon by [addon template](https://open-cluster-management.io/developer-guides/addon/#build-an-addon-with-addon-template) and provide an `AddonPlacementScore` to make placement decision based on GPU/TPU resources. We also want you to propose a customized external Kueue Admission Check controller to consume the placement decision to schedule AI workload among multiple clusters based on GPU/TPU resources. 

**Expected Outcome** 

- Develop the GPU/TPU resource collector addon, which includes documentation of the addon architecture and describing the `AddonPlacementScore` usage. Also, implement the addon using the addon template and contribute the code to the [addon-contrib](https://github.com/open-cluster-management-io/addon-contrib/tree/main/) repository.

- Deliver a proposal for the external Kueue Admission Check controller. The proposal should outline the API design and explain how the controller uses the OCM scheduling result and interacts with Kueue. The proposal needs to be finally reviewed in OCM community meeting. Also, you need to deliver a prototype based on the proposal. 

**Recommended Skills**

 Golang, Kubernetes, Scheduling

**Mentor(s)**

Qing Hao (@haoqing0110, [qhao@redhat.com](mailto:qhao@redhat.com)) - primary
Jian Qiu (@qiujian16, [jqiu@redhat.com](mailto:jqiu@redhat.com))

**References**
[Open Cluster Management](https://open-cluster-management.io/concepts/)
[Placement concept](https://open-cluster-management.io/concepts/placement/)
[AddOn concept](https://open-cluster-management.io/concepts/addon/)
[Placement extensible scheduling mechanism](https://open-cluster-management.io/scenarios/extend-multicluster-scheduling-capabilities/)
[Build an addon with addon template](https://open-cluster-management.io/developer-guides/addon/#build-an-addon-with-addon-template)
GPU on *KS, for example [GPUs in GKE](https://cloud.google.com/kubernetes-engine/docs/concepts/gpus) 
Kueue [Admission Check](https://kueue.sigs.k8s.io/docs/concepts/admission_check/) 

**Discussion**
Feel free to raise your questions here. Can also reach out to us in the [slack channel](https://kubernetes.slack.com/channels/open-cluster-mgmt). Failed to join by the link? See solutions at https://github.com/open-cluster-management-io/ocm/issues/369#issuecomment-1988798011 .

**Comment by Sayanjones** [comment]
Hi @haoqing0110, I am interested to work on this project. Can we discuss this further?

**Comment by Sayanjones** [comment]
I gone through the project, I got to know that it requires an addon to collect and score clusters based on GPU/TPU(contribute to ```addon-contrib```). Propose an external Kueue Admission Check controller that uses OCM's placement decisions for scheduling (community review needed).

**Comment by z1ens** [comment]
Hello @haoqing0110 :)
I am really interested in this GSoC project and looking forward to contribute useful code to OCM.   ## About me: My name is Zhe Shen, and I am a third year undergraduate student of computer science in Germany. I am familiar with GO and also Kubernetes, I recently done a project to build a FaaS which integrated with Kubernetes environment from scratch, which can deploy functions, manage them and scale them easily.

## I went through the OCM official page and tried some of the functions, including installing OCM, deploy Kubernetes resources on a specific cluster(Manifestwork)  on a cluster, and also tried to create a Placement to manage set of cluster(distribute the deployments in both clusters), and they all done successfully. ## After researching about addon templates, I have a few questions:   1.  How will the AddonPlacementScore algorithm evaluate clusters based on their GPU/TPU resources? What factors will it consider( utilization rates? Custom Metrics )?
2. How will the AddonPlacementScore integrate with existing OCM scheduling mechanisms?
3. How can we ensure the addon and controller are compatible with different Kubernetes distributions and versions?
##
All in all, I am aware that this project is more challenging then building a FaaS, and I am ready to learn and work on it! Thank you for your attention to read through it, looking forward to your reply.
p.s. I have noticed that in the website of OCM you are supporting documentation language in Chinese, I can try to maintain them as well since it’s my mother-language.

**Comment by haoqing0110** [comment]
Hello @Sayanjones @z1ens, thanks for being interested in this project. Feel free to join our community [slack channel](https://kubernetes.slack.com/channels/open-cluster-mgmt) if you want to have further discussion.  

----- 
@z1ens Thank you for your question, below are some of my thought: 
1. The most basic is by the allocatable resource, as well as the usage. Metrics is a good idea, could do some investigation to see if it‘s feasible.
2. The scheduling is logically divided into two phases internally: Predicate and Prioritize, using AddonPlacementScore to select the clusters one part of the progress. Hope the placement concept [page](https://open-cluster-management.io/concepts/placement/) makes it clear. And from code level, can refer to https://github.com/open-cluster-management-io/ocm/blob/main/pkg/placement/plugins/addon/addon.go to see how it works. 
3. In most cases I think a k8s upgrade should ensure its backward compatibility, and we also need to pay attention to any breaking changes.

**Comment by haoqing0110** [comment]
cc @qiujian16

**Comment by Sayanjones** [comment]
Hey @haoqing0110  I'm not able to join the slack channel. Please do the needful.

**Comment by k2nt** [comment]
Hi @mikeshng. Thank you for your email (and post)! I hope you can point me to the correct channel for this project (I assume that it is *open-cluster-mgmt*). I am posting here instead of replying via email so that other contributors can see this also.

**Comment by z1ens** [comment]
Hello, @haoqing0110 
Thank you for your patience to answer my questions, your ideas sounds inspiring, I will take a look at the code, and I just joined the slack channel right now. Have a nice day!

**Comment by zhy76** [comment]
Hello, I am a student of SEL Lab of Zhejiang University, and I am concerned about multi-cloud cluster management. I am currently a Karmada member and sealer reviewer. I am very interested in this project!

**Comment by haoqing0110** [comment]
This has been selected to participate in this year's Google Summer of Code! 🎉 https://github.com/cncf/mentoring/discussions/1221

**Comment by ivan-cai** [comment]
@qiujian16 @haoqing0110 resource-usage-collect agent needs to consider the available resources of each node, ometimes the cluster resources are sufficient, but the node resources are insufficient.

**Comment by haoqing0110** [comment]
@ivan-cai yes, I suppose @z1ens 's PR https://github.com/open-cluster-management-io/addon-contrib/pull/20 has changed to calculate the score based on the max node resource. We also had a discussion about whether need both cluster resource score and node resource score, it seems node resource score is more useful.

**Comment by haoqing0110** [comment]
Congratulations to @z1ens for completing the Google Summer of Code 2024 and contributing to the Open Cluster Management community. 

The following PRs have been merged to our repos:
[GPU/TPU-resource-usage-collect-addon](https://github.com/open-cluster-management-io/addon-contrib/pull/20) 
[OCM Kueue Admission Check Controller](https://github.com/open-cluster-management-io/ocm/pull/601)

These contributions are also an important part of two KubeCon topics.
[Connecting the Dots: Towards a Unified Multi-Cluster AI/ML Experience](https://kccncossaidevchn2024.sched.com/event/1eYXc/connecting-the-dots-towards-a-unified-multi-cluster-aiml-experience-pu-daepyu-ni-zha-zhong-shi-aimlmo-qing-hao-redhat-chen-yu-microsoft?iframe=no&w=100%25&sidebar=yes&bg=no)
[Boundaryless Computing: Optimizing LLM Performance, Cost and Efficiency in Multi-Cloud Architecture](https://kccncossaidevchn2024.sched.com/event/1eYXG/boundaryless-computing-optimizing-llm-performance-cost-and-efficiency-in-multi-cloud-architecture-yi-dui-dou-zhao-daepnano-llmxia-reyi-jian-zhu-red-hat-kai-zhang-alibaba-cloud-intelligence)  

Thanks again for your contributions!
