### ISSUE TITLE
improve the user scenarios in website

### ISSUE THREAD

**Issue by haoqing0110** [open-cluster-management-io/ocm#37]
We now have some user scenarios under https://open-cluster-management.io/scenarios/ , which may not be enough. 

And we have below feedback from users, which can help improve the user scenarios
- I want to know how OCM is used in the real world.
- Can OCM dispatch jobs for multi-cluster env? not clear about what can it do and how.
- I need some detailed usage of the core functions (such as a blog for that).
- To deploy an application on multiple clusters, I would want an easy approach.
- How to integrate with the app or other middleware? e.g. kubeflow

Create this issue to further discuss this topic. 
More ideas and suggestions are welcomed to comment on this issue. 

--------

Subtasks:
- #32
- #33
  - #58
  - #59
  - #60
  - #61
- #34
- #35
- #44

**Comment by xuezhaojun** [comment]
Please add subtask: https://github.com/open-cluster-management-io/OCM/issues/44

**Comment by xuezhaojun** [comment]
@qiujian16  Should this https://github.com/open-cluster-management-io/OCM/issues/44 document in the repo https://github.com/open-cluster-management-io/OCM 's solutions part or in the repo https://github.com/open-cluster-management-io/open-cluster-management-io.github.io? or both?

**Comment by xuezhaojun** [comment]
> @qiujian16 Should this #44 document in the repo https://github.com/open-cluster-management-io/OCM 's solutions part or in the repo https://github.com/open-cluster-management-io/open-cluster-management-io.github.io? or both?

It seems like this task is more suitable for OCM repo.

**Comment by haoqing0110** [comment]
Close as all sub-tasks are done.
