### ISSUE TITLE
Delete of manifestwork object can take up to 5min

### ISSUE THREAD

**Issue by effi-ofer** [open-cluster-management-io/ocm#379]
**Describe the bug**

When deleting a manifestwork object it can take up to 5min for the delete to complete.  To reproduce, in a loop I create a manifestwork object and almost immediately delete it.

Results for first delete:
real 0m10.417s
user 0m0.105s
sys 0m0.020s

Results for second delete:
real 4m5.973s
user 0m0.090s
sys 0m0.083s

Results for a third delete:
real 2m8.092s
user 0m0.088s
sys 0m0.053s

This only happens if the delete immediately follows a create.

**To Reproduce**

- Create OCM environment based on instructions here: https://open-cluster-management.io/getting-started/quick-start/
- Run the following: time kubectl --context kind-hub create -f d.yaml ; time kubectl --context kind-hub delete -f d.yaml
Where d.yaml is as defined as follows:
```
apiVersion: work.open-cluster-management.io/v1
kind: ManifestWork
metadata:
  annotations:
    transport.kubestellar.io/originOwnerReferenceBindingGeneration: "1"
  creationTimestamp: "2024-03-17T13:55:26Z"
  generation: 1
  labels:
    transport.kubestellar.io/originOwnerReferenceBindingKey: nginx
    transport.kubestellar.io/originWdsName: wds1
  name: nginx-wds1
  namespace: cluster1
  resourceVersion: "1274"
  uid: 670e80ba-9cd3-49f5-a277-d9c031ffc039
spec:
  workload:
    manifests:
    - apiVersion: v1
      kind: Namespace
      metadata:
        creationTimestamp: "2024-03-17T13:46:15Z"
        labels:
          app.kubernetes.io/name: nginx
          kubernetes.io/metadata.name: nginx
        name: nginx
      spec:
      status:
        phase: Active
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        creationTimestamp: "2024-03-17T13:54:09Z"
        labels:
          app.kubernetes.io/name: nginx
        name: nginx
        namespace: nginx
      spec:
        progressDeadlineSeconds: 600
        replicas: 4
        revisionHistoryLimit: 10
        selector:
          matchLabels:
            app: nginx
        strategy:
          rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
          type: RollingUpdate
        template:
          metadata:
            creationTimestamp: null
            labels:
              app: nginx
          spec:
            containers:
            - image: public.ecr.aws/nginx/nginx:latest
              imagePullPolicy: Always
              name: nginx
              ports:
              - containerPort: 80
                name: http
                protocol: TCP
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
            dnsPolicy: ClusterFirst
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
      status: {}
```

**Expected behavior**
The manifestwork object is deleted within a few seconds.

**Environment ie: OCM version, Kubernetes version and provider:**
$ clusteradm version
client          version :v0.8.0
server release  version :v1.25.3
default bundle  version :0.13.0

kind v0.17.0 go1.19.2 linux/amd64
Everything running on ubunty 22.04 hosted on windows 11 WSL2.

**Additional context**

**Comment by effi-ofer** [comment]
Just to be clear, following the delete the manifest object is marked with deletionTimestamp and then it seems that we wait up to 5min for the finalizers to finish.

**Comment by qiujian16** [comment]
I will try to reproduce this. My guess is ns seletion takes time, and ManiestWork wait until ns is fully deleted.

**Comment by effi-ofer** [comment]
Hi @qiujian16 have you managed to reproduce?

**Comment by qiujian16** [comment]
oh yes partly I can reproduce it. The major pending time is from namespace deletion, the manifestwork will wait until the namespace is fully cleaned by kube, then the finalizer will be removed.
