### ISSUE TITLE
Enhance the contributor ladder to better attract and motivate developers.

### ISSUE THREAD

**Issue by xuezhaojun** [open-cluster-management-io/ocm#390]
This enhancement aim to redesign our contributor ladder to better attract new contributors and motivate them.

Here list issue we found, and put them in different stage:

## Under discussion

- Lower the bar for each contributor level
- Introduce a new role for inactive maintainers
- Eliminate the reviewer role since it is not being used; consider adding a "lead" role for each area
- Consider treating addons as a special interest group.

## TODO

- 

## InProgress

- 

## Review

- 

Anyone can put your thought as comments under this issue, the description of the issue will capture the overall progress.

**Comment by qiujian16** [comment]
@xuezhaojun would you write a summary based on the discussion in the last community meeting? Including some questions that you have raised.
