### ISSUE TITLE
enhance cloudevents sdk to support garbage collection mechanism like kube

### ISSUE THREAD

**Issue by morvencao** [open-cluster-management-io/ocm#391]
**Describe the enhancement**

The current cloudevent sdk lacks support for garbage collection (GC) mechanisms similar to Kubernetes. When transporting manifestworks through cloudevents drivers, there's no automatic garbage collection process akin to Kubernetes. For instance, in cases of cascading deletion, where a manifestwork is associated with an owner reference, the manifestwork should ideally be deleted in the background when the owner is deleted. However, this functionality is absent in the current implementation.

We need to enhance the cloudevents sdk to include garbage collection capabilities, ensuring efficient resource management in cloudevents contexts.

/cc @qiujian16 @skeeey

**Comment by qiujian16** [comment]
the PR is merged
/close
