### ISSUE TITLE
How to apply a workload to many clusters? Do I have to create multiple ManifestWorks?

### ISSUE THREAD

**Issue by mrningyang** [open-cluster-management-io/ocm#41]
If i want to apply a deployment to cluster a and b, do I have to create two ManifestWorks to apply the deployment to cluster a and cluster b? If i want to update the workload, do I have to update all the ManifestWorks about the workload?

**Comment by mikeshng** [comment]
Yes, if you just use ManifestWork.
ManifestWork is meant to be a primitive work delivery API. Orchestration capability is not built into it.
You can check out our enhancement proposal for a higher level of orchestration PlacementWork in:
https://docs.google.com/document/d/17YZ3gvaakVWcavktGaVBNq5QUkMWlxge4zVe-rV43FM/edit#
https://www.youtube.com/watch?v=X181PoP3lpc

Alternatively, you can use our app addon or policy addon which allows you have delivery workload to your desired managed clusters as well. See: 
https://open-cluster-management.io/getting-started/integration/app-lifecycle/
https://open-cluster-management.io/getting-started/integration/policy-framework/
https://open-cluster-management.io/getting-started/integration/policy-controllers/

**Comment by mrningyang** [comment]
> app addon or policy addon

I do not think app addon or policy addon can help me. In fact, i think the designs of manifestWork and placement is vague. It seems manifestWork has decided the workload should be applied to which cluster. So, it means if we want to  build  orchestration capability based on OCM, should we generate manifestWork after the workload has been scheduled by placement? It seems OCM doesn't tell us how to use manifestWork and placement.

**Comment by mrningyang** [comment]
> Yes, if you just use ManifestWork. ManifestWork is meant to be a primitive work delivery API. Orchestration capability is not built into it. You can check out our enhancement proposal for a higher level of orchestration PlacementWork in: https://docs.google.com/document/d/17YZ3gvaakVWcavktGaVBNq5QUkMWlxge4zVe-rV43FM/edit# https://www.youtube.com/watch?v=X181PoP3lpc
> 
> Alternatively, you can use our app addon or policy addon which allows you have delivery workload to your desired managed clusters as well. See: https://open-cluster-management.io/getting-started/integration/app-lifecycle/ https://open-cluster-management.io/getting-started/integration/policy-framework/ https://open-cluster-management.io/getting-started/integration/policy-controllers/

I do not think app addon or policy addon can help me. In fact, i think the designs of manifestWork and placement is vague. It seems manifestWork has decided the workload should be applied to which cluster. So, it means if we want to build orchestration capability based on OCM, should we generate manifestWork after the workload has been scheduled by placement? It seems OCM doesn't tell us how to use manifestWork and placement.

**Comment by qiujian16** [comment]
yes, we are still investigating a higher primitive that integrates manifestwork/placement. Some work is here https://docs.google.com/document/d/17YZ3gvaakVWcavktGaVBNq5QUkMWlxge4zVe-rV43FM/edit#heading=h.ijzixgc4v32h  
We did not have a  default orchestration API since we found that this layer could have many different requirements from users which is not easy to generalize. We want to be more careful on this.

manifestwork and placement are very basic API that could be used to develop different features, e.g. currently it is mainly used to deploy and manage addons. They are also used in other projects like kubevela and argocd.

**Comment by qiujian16** [comment]
We were discussing also whether it makes more sense we should provide a go sdk to consume manifestwork/placement instead of a higher primitive. This could be helpful if a developer would like to build their own orchestration upon ocm.

**Comment by mrningyang** [comment]
> We were discussing also whether it makes more sense we should provide a go sdk to consume manifestwork/placement instead of a higher primitive. This could be helpful if a developer would like to build their own orchestration upon ocm.
Ok, thank you, I see

**Comment by zhujian7** [comment]
There is a new API introduced from v0.11.0, the [ManifestWorkReplicaSet](https://open-cluster-management.io/concepts/manifestworkreplicaset/), which can use [Manifestwork](https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/blob/main/content/en/concepts/manifestwork.md) and [Placement](https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/blob/main/content/en/concepts/placement.md) to create manifeswork for the placement selected clusters.

**Comment by qiujian16** [comment]
We have manifesworkReplicaSet now

/close
