### ISSUE TITLE
run ocm control plane as a standalone binary

### ISSUE THREAD

**Issue by qiujian16** [open-cluster-management-io/OCM#43]
It will be interesting to run ocm control plane in stand alone mode. It will involve integrating apiserver/controller/etcd in one single binary. We should also disable unused APIs on apiserver (e.g. nodes, pods etc.). We can start with a prototype and check how kcp does this.

cc @yue9944882 @ycyaoxdu 
/kind feature

**Comment by yue9944882** [comment]
@qiujian16 thanks, another obstacle in standalone mode is how to scale out etcd. i think we could probably start by leveraging an etcd-operator to make it dynamically scalable?

**Comment by qiujian16** [comment]
leaving items to resolve:

- [ ] refine the video demo and upload to youtube. @ycyaoxdu 
- [ ] resolve unexpected informer error. @ycyaoxdu 
- [ ] consider create a repo in ocm or using ocm/ocm to host the control plane code @qiujian16 
- [ ] identify gap in the current code @ycyaoxdu

**Comment by ycyaoxdu** [comment]
video uploaded. https://www.youtube.com/watch?v=fTaU9dncgHY @qiujian16

**Comment by ycyaoxdu** [comment]
the unexpected informer error bug fixed @qiujian16

**Comment by ycyaoxdu** [comment]
use external etcd allowed @qiujian16

**Comment by ycyaoxdu** [comment]
add `TODO(ycyaoxdu)` comment to label refinable codes  https://github.com/ycyaoxdu/ocm-control-plane/commit/e5bc0ca4d468c06f94e8c8a58313cc6d885990a9
