### ISSUE TITLE
Fix: `bitnami` repos turn to unavailable.

### ISSUE THREAD

**Issue by xuezhaojun** [open-cluster-management-io/OCM#45]
Here are all places we replying on `bitnami` repos:
https://github.com/search?q=org%3Aopen-cluster-management-io+bitnami&type=code

We should remove all dependencies later.

**Comment by xuezhaojun** [comment]
cc @qiujian16 @zhiweiyin318

**Comment by mikeshng** [comment]
I will fix the ones that are related to app repo(s).

**Comment by xuezhaojun** [comment]
All images are replaced.
/close
