### ISSUE TITLE
Provide Helm charts for OCM components

### ISSUE THREAD

**Issue by mikeshng** [open-cluster-management-io/ocm#46]
Thanks to Min Kim's excellent work, there is now a centralize OCM repo containing OCM related Helm charts: https://github.com/open-cluster-management-io/helm-charts

So far there are only some addon Helm charts. We should have Helm charts for core components (cluster manager, klusterlet) as well as some other addon charts (app, grc). 

This enhancement is related to https://github.com/open-cluster-management-io/OCM/issues/40

**Comment by grzesuav** [comment]
hi @mikeshng do you have any idea (or know where to look) for set of manifest/objects required both for hub and klusterjet ? 
I mean core components (namespace deployment etc) and RBAC.

**Comment by grzesuav** [comment]
Actually just looked at https://github.com/open-cluster-management-io/registration-operator and it seems it can be a starting point

**Comment by mikeshng** [comment]
Hi @pajikos we still don't have an easy way to bootstrap using helm because there are too many manual steps involved when it comes to cluster registration. The helm charts doesn't provide much except for laying down the ocm components on hub and managed clusters.

**Comment by qiujian16** [comment]
this has actually been achieved. we will have the chart uploaded in 0.15.0 release.
