### ISSUE TITLE
The addonProcessController should consider the hosting case.

### ISSUE THREAD

**Issue by xuezhaojun** [open-cluster-management-io/ocm#461]
**Describe the bug**

There are mainly 2 place not considering the hosted mode in the addonProcessController:

## 1

https://github.com/stolostron/ocm/blob/6430b333e7f19c9faeab78c1e6aa41f9b4d64c26/pkg/addon/controllers/addonprogressing/controller.go#L135

The controller will wait for `ManagedClusterAddOnManifestApplied` but for hosted mode, there will only be a `HostingManifestApplied `. 

As a result the there will always be Waiting condition for the addon.
![image](https://github.com/open-cluster-management-io/ocm/assets/11444421/2692f230-3c07-46a9-9978-b4fdb09e2f31)

## 2

https://github.com/stolostron/ocm/blob/6430b333e7f19c9faeab78c1e6aa41f9b4d64c26/pkg/addon/controllers/addonprogressing/controller.go#L155

From the comment we can see there is a TODO to consider hosted manifestwork.

The hosted addon will always show "no addon works" and hang in Processing is true state: https://github.com/stolostron/ocm/blob/6430b333e7f19c9faeab78c1e6aa41f9b4d64c26/pkg/addon/controllers/addonprogressing/controller.go#L165

**Comment by qiujian16** [comment]
@zhujian7 I think we have fixed this?

**Comment by zhujian7** [comment]
yes, https://github.com/open-cluster-management-io/ocm/pull/464

**Comment by xuezhaojun** [comment]
add addon-framework PR https://github.com/open-cluster-management-io/addon-framework/pull/267
