### ISSUE TITLE
Apply all labels that klusterlet has to all the resources it will create and keep labels in sync

### ISSUE THREAD

**Issue by EricaJ6** [open-cluster-management-io/ocm#467]
**Describe the enhancement**
We observed that resources created by klusterlet do not have labels that klusterlet has. For example, `klusterlet-agent` in the `open-cluster-management-agent` namespace is missing labels. We’re using these labels for cost tracking purposes. As discussed with @qiujian16, and agreed to apply all labels that klusterlet has to all the resources it will create. Additionally, if labels on the klusterlet got changed (either updated or added new ones), all the resources created by it should be in sync as well.

**Comment by qiujian16** [comment]
@zhiweiyin318 will you be able to take a look at this one?

**Comment by zhiweiyin318** [comment]
@EricaJ6 @qiujian16  I have some questions about this requirement.
1. just double check that we need to sync the label to the all agent resources or only deployments since the description mentioned ` cost tracking purposes`.
2. do we need delete the label from the agent if it  is removed from the klusterlet ? the reason why I ask is currently the map update strategy is merge.

**Comment by EricaJ6** [comment]
Thanks @zhiweiyin318! For your questions,
1. We should sync the labels to all resources created by the klusterlet. The goal is all resources should have the necessary labels. I looked into the above PR, it looks like currently, only deployments have labels added, could you please add labels to all resources (such as `spec. template. metadata.labels` and so on)?
2. If the label got removed from the klusterlet, it should also be removed from all resources created by the klusterlet.

**Comment by zhiweiyin318** [comment]
@EricaJ6  currently there are 2 labels `app: klusterlet-agent`  and `createdBy: klusterlet `on the deployment created by klusterlet.
if we add the 2 labels to all agent resources, not sure if can meet your requirements for cost tracking purpose?
if the 2 labels can meet your requirements, I think it is not necessary to sync labels from klusterlet.

**Comment by EricaJ6** [comment]
@zhiweiyin318 Other than the 2 default labels, we are adding additional customization labels to klusterlet, and the organization is using these customized labels for cost-tracking purpose. That's why we would like to sync the labels to all resources created by the klusterlet. Because of the use of additional customization labels, the 2 default labels do not meet the requirements.

**Comment by EricaJ6** [comment]
Thanks @zhiweiyin318 on sharing the information and updating the PR! 

1.  To make sure all pods created by the deployments also have the labels, how about adding labels to the `spec.template.metadata.labels` of the `*deployment.yaml` files as well?
2. Will [clusteradm repo](https://github.com/open-cluster-management-io/clusteradm/tree/main) also needs to be updated for synced labels to take effect?

**Comment by zhiweiyin318** [comment]
@EricaJ6  
1. Added labels for pods.
2. I don't think [clusteradm repo](https://github.com/open-cluster-management-io/clusteradm/tree/main) need to be updated since the latest image will take affect after the PR is merged. you can add labels to klusterlet after the cluster is joined to the hub.

**Comment by EricaJ6** [comment]
@zhiweiyin318 

1. The pods' labels look good!
2. Is there a timeline for when the PR will be released? We'll try it out.

**Comment by zhiweiyin318** [comment]
the feature will be included into release v0.14.0. you can try it using the latest images after the PR is merged.

**Comment by zhiweiyin318** [comment]
@EricaJ6 The PR is merged. please use the latest images to take a try.

**Comment by EricaJ6** [comment]
Thanks @zhiweiyin318 for the updates! I will try it once it is released.
