### ISSUE TITLE
Why are there three klusterlet pods in a managed cluster?(problem)

### ISSUE THREAD

**Issue by Willy1999927** [open-cluster-management-io/ocm#479]
In the cluster I have with one master and two workers, why are there three klusterlet pods used to pull the configuration and execute it? Do you have a complete architecture diagram?

xxx@xxx:/home/cdlab# kubectl get pods -n open-cluster-management -o wide
NAME                         READY   STATUS    RESTARTS       AGE   IP              NODE   NOMINATED NODE   READINESS GATES
klusterlet-67d4cdc69-5mms5   1/1     Running   16 (16h ago)   29d   10.244.43.1     worker1   <none>           <none>
klusterlet-67d4cdc69-bk49j   1/1     Running   4 (24h ago)    29d   10.244.43.2     wroker1   <none>           <none>
klusterlet-67d4cdc69-x75hk   1/1     Running   12 (16h ago)   29d   10.244.70.132   worker2   <none>           <none>

**Comment by qiujian16** [comment]
The number or replica is decided here https://github.com/open-cluster-management-io/ocm/blob/main/pkg/operator/helpers/helpers.go#L435. The is mainly for the HA case, and ensure the agent keeps on running during rolling upgrade.

**Comment by Willy1999927** [comment]
OK,thanks for your reply
