### ISSUE TITLE
Need more documentation for OCM troubleshooting

### ISSUE THREAD

**Issue by leipanhz** [open-cluster-management-io/ocm#50]
I am learning OCM recently, the feature is nice. We are interested in using OCM in our project to support multi-cluster communication. During my experiments and troubleshooting, I found it is difficult to understand the underlying meaning of error messages, and look for fixes of the issues. Luckily the contributors and developers of OCM are very knowledgeable and helpful, on the other hand, if there is well-documented troubleshooting guide, there will be time saving for developers and providing smoother user experience.

**Comment by mikeshng** [comment]
This is a really good idea. I think one of the first one we should add is: for `KinD` cluster setup, the `clusteradm join` command needs to be run with `--force-internal-endpoint-lookup` param.

Please feel free to add more recommendations for troubleshooting in this issue and we will append to the doc.

/assign mikeshng
