### ISSUE TITLE
Not able to disable/delete a ManagedClusterAddon

### ISSUE THREAD

**Issue by mikeshng** [open-cluster-management-io/ocm#53]
When a user install the cluster-proxy, managed-serviceaccount and cluster-gateway addons. The managed cluster addon resources are automatically created on the registered clusters. If the addons are deployed to cluster foo and bar. Is it possible to disable or delete the addons for cluster bar? Currently, when deleting those managed cluster addon on cluster bar namespace, they will come back.

```
$ kubectl get managedclusteraddon -n $NSC1
NAME                     AVAILABLE   DEGRADED   PROGRESSING
cluster-gateway          True
cluster-proxy            True
managed-serviceaccount   True
$ kubectl -n $NSC1 delete managedclusteraddon cluster-gateway
managedclusteraddon.addon.open-cluster-management.io "cluster-gateway" deleted

$ kubectl get managedclusteraddon -n $NSC1
NAME                     AVAILABLE   DEGRADED   PROGRESSING
cluster-gateway          True
cluster-proxy            True
managed-serviceaccount   True
```

Discovered by @yitiangf 

CC @qiujian16

**Comment by qiujian16** [comment]
this is controlled by each addon controller separately. If it uses installAll strategy, the addon controller of the certain addon will alway enable it.

**Comment by qiujian16** [comment]
ah, another clean up issue...FYI @zhiweiyin318. We have a fix in addon-framework that if a cluster is deleting, addon should not be created again.

**Comment by zhujian7** [comment]
I think we can add an annotation filter functionality to the addon-framework to filter managedclusters when using install strategy. If a managed cluster has annotation `addon.open-cluster-management.io/disable-automatic-installation: "true"`, the install strategy will ignore it when deploying addons.

**Comment by zhujian7** [comment]
The PR adding annotation addon.open-cluster-management.io/disable-automatic-installation: "true" to disable the addon auto installation has been merged.
BTW, The installAll strategy has been deprecated, instead, there is a new feature introduced from v0.11.0, [Enable the add-on by install strategy](https://open-cluster-management.io/concepts/addon/#enable-the-add-on-by-install-strategy) which can enable addons based on selected clusters.
