### ISSUE TITLE
Add Test Coverage to improve code quality.

### ISSUE THREAD

**Issue by xuezhaojun** [open-cluster-management-io/OCM#56]
It's better to have test coverage to improve our code quality. 

There are several things we could do:
1. Add GitHub action check for new PR to meet the coverage requirement.
2. Set a goal (for example 70%) for further code-refactor tasks.
3. etc.

**Comment by qiujian16** [comment]
is this a task?

**Comment by xuezhaojun** [comment]
Not sure about the scope yet, mainly used to record discussion in the coming community meeting about the topic.
