### ISSUE TITLE
Addon namespace created without any addon installed.

### ISSUE THREAD

**Issue by xuezhaojun** [open-cluster-management-io/ocm#64]
After deploy `klusterlet`, we found `open-cluster-management-agent-addon` is created but yet we had not installed any addons.

We think the related code is: https://github.com/stolostron/registration-operator/blob/99db7a66e63e1c96b585b4aa22ad923e198c1028/pkg/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller.go#L339

So if it possible only create this ns if addons exists?

**Comment by xuezhaojun** [comment]
cc @elgnay

**Comment by zhujian7** [comment]
I think this is by design, the klusterlet creates the namespace and is responsible for copying the pull image secret to the namespace.
