### ISSUE TITLE
provide a normalize library to generate scores for AddOnPlacementScore

### ISSUE THREAD

**Issue by haoqing0110** [open-cluster-management-io/ocm#68]
In https://open-cluster-management.io/scenarios/extend-multicluster-scheduling-capabilities/ ,we talked about how to calculate and normalize the score for AddOnPlacementScore, it's better to provide a normalize library to do it.

Ref: https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/pull/280#discussion_r945398814

**Comment by qiujian16** [comment]
this could be put into sdk-go
