### ISSUE TITLE
Allow Custom Signer signingCA to Specify Namespace in AddOnTemplate

### ISSUE THREAD

**Issue by mikeshng** [open-cluster-management-io/ocm#688]
**Describe the enhancement**
In the current [AddOnTemplate API](https://github.com/open-cluster-management-io/api/blob/v0.15.0/addon/v1alpha1/types_addontemplate.go#L182-L188), the `SigningCARef` does not allow for specifying a namespace value. This means the signing CA secret must be in the `open-cluster-management-hub` namespace where the addon-manager-controller resides.

In some cases, such as when the argocd-agent principal deployment needs to leverage the signing CA secret, the current restriction forces users to place the argocd-agent deployment in the `open-cluster-management-hub` namespace instead of its intended `argocd` namespace. 

Requesting an enhancement to add a namespace field in `SigningCARef`, allowing it to reference a signing CA secret in a specified namespace. Users are still required for granting the necessary RBAC permissions (same as now).

**Comment by mikeshng** [comment]
CC @qiujian16 @zhujian7 @xuezhaojun

**Comment by zhujian7** [comment]
@mikeshng This feature has been implemented, I will close this issue, feel free to have a try.
/close
