### ISSUE TITLE
Work supports wildcard for the name/namespace fields in the ResourceIdentifier of ManifestConfigOption

### ISSUE THREAD

**Issue by zhiweiyin318** [open-cluster-management-io/ocm#705]
**Describe the enhancement**
In the addon case, the user may have no idea the real namespace/name of a manifest in a workManifest before the wokManifest of the addon is created, so the user could not configure the specified ResourceIdentifier of ManifestConfigOption to FeedbackRules for healthProber.

This case can be addressed If the name/namespace in the ResourceIdentifier of ManifestConfigOption can support wildcard.

Another benefit is that it will be easy to configure a bunch of the same type of resources in ManifestConfigOption.

**Comment by zhiweiyin318** [comment]
cc @tesshuflower feel free to append the details about the use case.

**Comment by tesshuflower** [comment]
Thanks @zhiweiyin318 ! I think that describes it well - at the time we instantiate the addonagent using the addon-framework, that is when we need to provide the ProbeFields for the prober, which require the information about the resource we want to probe, including name and namespace.  At our controller startup time, we don't necessarily know this and they could be different for different managed clusters.
