### ISSUE TITLE
Please fix CVE - https://github.com/advisories/GHSA-v778-237x-gjrc

### ISSUE THREAD

**Issue by dongbeiqing91** [open-cluster-management-io/ocm#773]
Please fix CVE - https://github.com/advisories/GHSA-v778-237x-gjrc
golang.org/x/crypto: Affected versions < 0.31.0, Patched versions 0.31.0
Thanks!

**Comment by zhujian7** [comment]
OCM does not use the `ServerConfig.PublicKeyCallback callback`, so it will not be impacted.
But we will still bump the golang.org/x/crypto to 0.31.0 by PR: https://github.com/open-cluster-management-io/ocm/pull/774
