### ISSUE TITLE
Does the community have a standard way of calculating code coverage?

### ISSUE THREAD

**Issue by gparvin** [open-cluster-management-io/ocm#85]
We would like to know if this community has a standard way of checking code coverage.  We are using a script now at least in this repository: https://github.com/open-cluster-management-io/governance-policy-propagator/blob/main/build/common/scripts/coverage_calc.sh

Are there other code quality checks that are recommended for OCM too?

**Comment by qiujian16** [comment]
@xuezhaojun is investigating codecov, and it is used in cluster-proxy already. We would consider using codecov across the community.

**Comment by xuezhaojun** [comment]
@gparvin Hi, Gus, it‘s easy to setup a coverage check in github actions, there is a PR you can refer to: https://github.com/open-cluster-management-io/cluster-proxy/pull/150/files

But we don't set a restrictive rule at this point in time. Repo owners can decide by themselves what target and threshold are reasonable for their projects.
