### ISSUE TITLE
Run multiple OCM instances in a single Kubernetes cluster

### ISSUE THREAD

**Issue by clyang82** [open-cluster-management-io/ocm#99]
Propose to have a `standalone-controlplane` repo to serve for:
1. run multiple OCM instances in the different namespaces in a single Kubernetes cluster. Each instance is running in a pod in one namespace.
2. Each OCM instance exposes the endpoint so that the cluster can be able to register into as a managed cluster.
3. The lightweight controlplane instance can be started in a very short time. It is more easy to consume.

In this way, we can scale out to support more managed clusters. In other words, the single cluster with multiple OCM instances can support more managed clusters than a single OCM cluster does.

FYI @qiujian16

**Comment by mikeshng** [comment]
This is great! +1

Just a suggestion, I feel like the name `multicluster-controlplane` might be better for marketing than `standalone`.
In my personal experience, standalone sounds like something that is for development purpose and fits into your point 3. light weight but I wouldn't think that using it will have the benefits of: "the single cluster with multiple OCM instances can support more managed clusters than a single OCM cluster does."

This is something that we should present in the SIG multicluster meeting as well. There were some community feedback during KubeCon NA that users are looking for multicluster control plane like solutions. So if we can name it `multicluster-controlplane` we can capture the attention of the community easier.

Just my opinion. I am ok with `standalone` if you think it's better.

**Comment by qiujian16** [comment]
the code and demo script is here https://github.com/open-cluster-management-io/OCM/tree/standalone-controlplane. I think we should also do a demo in the community @clyang82

**Comment by clyang82** [comment]
Thanks @mikeshng I like `multicluster-controlplane` name.
Thanks @qiujian16 Please help me add a topic in this Friday's community meeting.

**Comment by qiujian16** [comment]
queued for next community meeting.

**Comment by mikeshng** [comment]
@clyang82 the community meeting is going to be on the Nov 25th and not this Friday. Just a FYI. Thanks.

**Comment by qiujian16** [comment]
@clyang82 could we make a doc to instruct how to enable and use this function?

**Comment by clyang82** [comment]
sure. let me make a doc soon.

**Comment by clyang82** [comment]
here is document for multicluster controlplane - https://open-cluster-management.io/concepts/multicluster-controlplane/
